/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsDate,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { AnamnesisUpdateManyWithoutConsultantsInput } from "./AnamnesisUpdateManyWithoutConsultantsInput";
import { Type } from "class-transformer";
import { FactureUpdateManyWithoutConsultantsInput } from "./FactureUpdateManyWithoutConsultantsInput";
import { ScriptUpdateManyWithoutConsultantsInput } from "./ScriptUpdateManyWithoutConsultantsInput";
import { EnumConsultantWhyTheyCome } from "./EnumConsultantWhyTheyCome";
@InputType()
class ConsultantUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AnamnesisUpdateManyWithoutConsultantsInput,
  })
  @ValidateNested()
  @Type(() => AnamnesisUpdateManyWithoutConsultantsInput)
  @IsOptional()
  @Field(() => AnamnesisUpdateManyWithoutConsultantsInput, {
    nullable: true,
  })
  anamneses?: AnamnesisUpdateManyWithoutConsultantsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  birthDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  comeFrom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => FactureUpdateManyWithoutConsultantsInput,
  })
  @ValidateNested()
  @Type(() => FactureUpdateManyWithoutConsultantsInput)
  @IsOptional()
  @Field(() => FactureUpdateManyWithoutConsultantsInput, {
    nullable: true,
  })
  factures?: FactureUpdateManyWithoutConsultantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  job?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  kids?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  married?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => ScriptUpdateManyWithoutConsultantsInput,
  })
  @ValidateNested()
  @Type(() => ScriptUpdateManyWithoutConsultantsInput)
  @IsOptional()
  @Field(() => ScriptUpdateManyWithoutConsultantsInput, {
    nullable: true,
  })
  scripts?: ScriptUpdateManyWithoutConsultantsInput;

  @ApiProperty({
    required: false,
    enum: EnumConsultantWhyTheyCome,
  })
  @IsEnum(EnumConsultantWhyTheyCome)
  @IsOptional()
  @Field(() => EnumConsultantWhyTheyCome, {
    nullable: true,
  })
  whyTheyCome?:
    | "HypnoRelaxation"
    | "LiberationEmotionnelle"
    | "DeveloppementPersonnel"
    | "Tabac"
    | "Addiction"
    | "Douleur"
    | "TroubleSexuel"
    | "Enfant"
    | "PerformanceSportive"
    | null;
}
export { ConsultantUpdateInput };
